*** Settings ***
Documentation
...    List of external RF libraries required.

Library    DatabaseLibrary
Library    DateTimeTZ
Library    FakerLibrary
Library    json
Library    JSONLibrary
Library    JsonValidator
Library    RequestsLibrary
Library    Browser    auto_closing_level=SUITE
# Library    RobotNotifications
# ...    https://hooks.slack.com/services/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
# ...    end_test
