name: Automated Thanos API Tests
on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 9,12,16 * * *'
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::890086007145:role/github-actions-testing-automation
        aws-region: eu-west-1

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - run: |
        npm install
        npm ci

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "requirements.txt"

    - name: Run Robot Frontend Tests via Pabot
      run: |
        pabot -d test_results -i thanos tests

    - name: Upload Test Results
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: test_results
        path: test_results/
        retention-days: 31
        overwrite: true

