name: Playwright Tests
on:
  push:
    branches: [ env_setup ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '^3.12'
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
          path: "requirements.txt"
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Robot Framework Tests
      run: robot -d results tests
