name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "env_setup" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setup Playwright
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps

      # Run Robot Framework Tests
      - name: Robot Framework
        run: |
          robot -d results tests
